name: Sync Commercial Blog

on:
  workflow_run:
    workflows: ["Deploy static content to Pages"]
    types:
      - completed

jobs:
  sync:
    if: ${{ github.event.workflow_run.conclusion == 'success' && vars.TARGET_REPO != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to target repository
        env:
          GITHUB_TOKEN: ${{ secrets.COMMERCIAL_REPO_PAT }}
          TARGET_REPO: ${{ vars.TARGET_REPO }}
        run: |
          git remote add commercial https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository_owner }}/${TARGET_REPO}.git
          git push commercial HEAD:main --force
